### PR TITLE
Add `emojilib` to enhance results

### LINKED ISSUE #30: Enhance 3rd party result with local information
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/emoj/issues/30)

Some emoji's just aren't findable with the 3rd party service. For instance https://github.com/sindresorhus/alfred-emoj/issues/14. What would it take to enhance the results?

Could we bundle a local db to add emoji that are hard to find or just aren't in the 3rd party service?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#39 solves #30](https://issuehunt.io/r/sindresorhus/emoj/pull/39)
- [#40 Add `emojilib` to enhance results](https://issuehunt.io/r/sindresorhus/emoj/pull/40)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/emoj/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by satyarohith**
closes #30

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#30: Enhance 3rd party result with local information](https://issuehunt.io/repos/61745494/issues/30)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by mesqueeb** [comment]
@satyarohith hi! Can I test this locally? I'd love to test it 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by satyarohith** [comment]
@mesqueeb Yes, you can test it. The only thing missing is offline support.

**Comment by satyarohith** [comment]
@sindresorhus Any thoughts on offline support (i.e. search without internet connection)? To support this feature, we need to do a little refactor but I don't think it will be worth it because most of the time everyone is connected to the internet. Let me know what you think. I will dig in if you think it's useful.

**Comment by revelt** [comment]
@sindresorhus please advise ^

**Comment by mesqueeb** [comment]
Why not merge this PR and open a new ticket for offline support.
Then we can already start using this feature and adding offline support or not can be decided in the new ticket. ;)

**Pull request closed without merging**
