### PR TITLE
Clear results when changing search query

### PR DESCRIPTION
**Pull request by vadimdemedes**
Fixes https://github.com/sindresorhus/emoj/issues/23.

### CODE REVIEW

**Comment by sindresorhus** [comment]
This also clear the result whenever the arrow moves.

**Comment by vadimdemedes** [comment]
Oops, will fix.

**Comment by vadimdemedes** [comment]
Fixed. Also fixed a bug, where arrow remained at the same place when new emojis loaded. Now it resets to zero, when there's a new search query.

**Comment by sindresorhus** [comment]
Works great :)

**Pull request merged**
